<?xml version="1.0" encoding="utf-8"?><Database Name="fntech_signage" Class="schedDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=172.16.1.65\FNTECH;Initial Catalog=fntech_signage;Persist Security Info=True;User ID=sa" SettingsObjectName="schedInterface.Properties.Settings" SettingsPropertyName="fntech_signageConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.sessions" Member="sessions">
    <Type Name="session">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="event_key" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="active" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="title" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="session_start" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="session_end" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="type" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="description" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="seats" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="attendees" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="venue_id" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="venue" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="speakers" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="created" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="modified" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="event_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.locations" Member="locations">
    <Type Name="location">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="sched_id" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="title" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="event_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.resolutions" Member="resolutions">
    <Type Name="resolution">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="title" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="width" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="height" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.[log]" Member="logs">
    <Type Name="log">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="event_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="logdate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="user_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="title" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="description" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.permissions" Member="permissions">
    <Type Name="permission">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="event_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="user_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="permission_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="assigned_date" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="assigned_by" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.security" Member="securities">
    <Type Name="security">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="title" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="description" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="active" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.users" Member="users">
    <Type Name="user">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="first_name" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="last_name" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="email" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="company" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="created" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="active" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="notify_every_minutes" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="pic" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="pwd" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="security" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.media" Member="medias">
    <Type Name="media">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="service" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="username" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="full_name" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="description" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="createdate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="profilepic" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="link" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="likes" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="latitude" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="longitude" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="approved" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="approved_by" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="approved_date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="added_to_db_date" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="location_name" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="source_id" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="width" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="height" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="is_video" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="source" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="tags" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="event_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="template_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.overlays" Member="overlays">
    <Type Name="overlay">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="title" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="preview" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="active" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="header" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="body" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="footer" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.messages" Member="messages">
    <Type Name="message">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="event_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="template_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="terminal_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="start" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="stop" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="entire" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="title" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="message" Member="message1" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="pic" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.templates" Member="templates">
    <Type Name="template">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="title" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="event_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="orientation" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="resolution" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="bgcolor" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="bgimage" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="overlay" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="overlay_font" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="overlay_font_color" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="rotate_ads" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="ad_interval" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="t_username" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="t_hashtag" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="video" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.decks" Member="decks">
    <Type Name="deck">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="event_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="title" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="description" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.slides" Member="slides">
    <Type Name="slide">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="deck_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="source" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="display" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.terminals" Member="terminals">
    <Type Name="terminal">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="title" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="location_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="template_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="online" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="event_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="last_online" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="deck" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="rotate" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.speakers" Member="speakers">
    <Type Name="speaker">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="first_name" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="last_name" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="title" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="bio" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="irc" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="twitter" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="member_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="pic" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="openstack_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="event_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.events" Member="events">
    <Type Name="event">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="title" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="event_start" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="event_end" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="api_key" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="url" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="interval" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="last_update" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="t_username" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="t_hashtag" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="openstack_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="offset" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.event_types" Member="event_types">
    <Type Name="event_type">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="event_type_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="title" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="event_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.settings" Member="settings">
    <Type Name="setting">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="value" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Function Name="dbo.permissions_get_by_user" Method="permissions_get_by_user">
    <Parameter Name="user_id" Type="System.Int32" DbType="Int" />
    <ElementType Name="permissions_get_by_userResult">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="event_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="user_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="permission_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="assigned_date" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="assigned_by" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="title" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="security_level" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="full_name" Type="System.String" DbType="VarChar(101)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.events_get_authorized" Method="events_get_authorized">
    <Parameter Name="user_id" Type="System.Int32" DbType="Int" />
    <ElementType Name="events_get_authorizedResult">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="title" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="event_start" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="event_end" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="api_key" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="url" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="interval" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="last_update" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.events_to_update" Method="events_to_update">
    <ElementType Name="events_to_updateResult">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="title" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="event_start" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="event_end" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="api_key" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="url" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="interval" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="last_update" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="t_username" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="t_hashtag" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.templates_by_event" Method="templates_by_event">
    <Parameter Name="id" Type="System.Int32" DbType="Int" />
    <ElementType Name="templates_by_eventResult">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="title" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="event_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="orientation" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="resolution" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="bgcolor" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="bgimage" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="overlay" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="overlay_font" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="overlay_font_color" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="rotate_ads" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="ad_interval" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="t_username" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="t_hashtag" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="overlay_title" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.session_get_current" Method="session_get_current">
    <Parameter Name="event_id" Type="System.Int32" DbType="Int" />
    <Parameter Name="location_id" Type="System.String" DbType="VarChar(255)" />
    <ElementType Name="session_get_currentResult">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="event_key" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="active" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="title" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="session_start" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="session_end" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="type" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="description" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="seats" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="attendees" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="venue_id" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="venue" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="speakers" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="created" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="modified" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="event_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.session_get_next" Method="session_get_next">
    <Parameter Name="event_id" Type="System.Int32" DbType="Int" />
    <Parameter Name="location_id" Type="System.String" DbType="VarChar(255)" />
    <Parameter Name="prev_end" Type="System.DateTime" DbType="DateTime" />
    <ElementType Name="session_get_nextResult">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="event_key" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="active" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="title" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="session_start" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="session_end" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="type" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="description" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="seats" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="attendees" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="venue_id" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="venue" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="speakers" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="created" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="modified" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="event_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.media_random_by_event" Method="media_random_by_event">
    <Parameter Name="id" Type="System.Int32" DbType="Int" />
    <ElementType Name="media_random_by_eventResult">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="service" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="username" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="full_name" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="description" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="createdate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="profilepic" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="link" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="likes" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="latitude" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="longitude" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="approved" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="approved_by" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="approved_date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="added_to_db_date" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="location_name" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="source_id" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="width" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="height" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="is_video" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="source" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="tags" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="event_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="template_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.messages_by_event" Method="messages_by_event">
    <Parameter Name="event_id" Type="System.Int32" DbType="Int" />
    <ElementType Name="messages_by_eventResult">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="event_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="template_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="terminal_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="start" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="stop" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="entire" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="title" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="message" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="pic" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.messages_by_terminal" Method="messages_by_terminal">
    <ElementType Name="messages_by_terminalResult">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="event_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="template_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="terminal_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="start" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="stop" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="entire" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="title" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="message" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="pic" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="terminal_title" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.messages_by_template" Method="messages_by_template">
    <ElementType Name="messages_by_templateResult">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="event_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="template_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="terminal_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="start" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="stop" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="entire" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="title" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="message" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="pic" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="template_title" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.messages_get_random" Method="messages_get_random">
    <Parameter Name="event_id" Type="System.Int32" DbType="Int" />
    <Parameter Name="template_id" Type="System.Int32" DbType="Int" />
    <Parameter Name="terminal_id" Type="System.Int32" DbType="Int" />
    <ElementType Name="messages_get_randomResult">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="event_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="template_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="terminal_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="start" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="stop" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="entire" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="title" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="message" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="pic" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.clean_design_summit" Method="clean_design_summit">
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.terminal_assignments_by_event" Method="terminal_assignments_by_event">
    <Parameter Name="id" Type="System.Int32" DbType="Int" />
    <ElementType Name="terminal_assignments_by_eventResult">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="title" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="location_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="template_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="online" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="event_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="last_online" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="deck" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="rotate" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="location_title" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="template_title" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sessions_by_event_location_date" Method="sessions_by_event_location_date">
    <Parameter Name="event_id" Type="System.Int32" DbType="Int" />
    <Parameter Name="location" Type="System.String" DbType="VarChar(255)" />
    <ElementType Name="sessions_by_event_location_dateResult">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="event_key" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="active" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="title" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="session_start" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="session_end" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="type" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="description" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="seats" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="attendees" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="venue_id" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="venue" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="speakers" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="created" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="modified" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="event_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sessions_remove" Method="sessions_remove">
    <Parameter Name="event_key" Type="System.String" DbType="VarChar(255)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.speaker_mod" Method="speaker_mod">
    <Parameter Name="first_name" Type="System.String" DbType="VarChar(255)" />
    <Parameter Name="last_name" Type="System.String" DbType="VarChar(255)" />
    <Parameter Name="title" Type="System.String" DbType="VarChar(MAX)" />
    <Parameter Name="bio" Type="System.String" DbType="VarChar(MAX)" />
    <Parameter Name="irc" Type="System.String" DbType="VarChar(MAX)" />
    <Parameter Name="twitter" Type="System.String" DbType="VarChar(MAX)" />
    <Parameter Name="member_id" Type="System.Int32" DbType="Int" />
    <Parameter Name="pic" Type="System.String" DbType="VarChar(MAX)" />
    <Parameter Name="openstack_id" Type="System.Int32" DbType="Int" />
    <Parameter Name="event_id" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.session_mod" Method="session_mod">
    <Parameter Name="event_key" Type="System.String" DbType="VarChar(255)" />
    <Parameter Name="active" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="title" Type="System.String" DbType="VarChar(MAX)" />
    <Parameter Name="session_start" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="session_end" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="type" Type="System.String" DbType="VarChar(255)" />
    <Parameter Name="description" Type="System.String" DbType="VarChar(MAX)" />
    <Parameter Name="seats" Type="System.Int32" DbType="Int" />
    <Parameter Name="attendees" Type="System.Int32" DbType="Int" />
    <Parameter Name="venue_id" Type="System.Int32" DbType="Int" />
    <Parameter Name="venue" Type="System.String" DbType="VarChar(255)" />
    <Parameter Name="speakers" Type="System.String" DbType="VarChar(MAX)" />
    <Parameter Name="event_id" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.design_summit_austin" Method="design_summit_austin">
    <ElementType Name="design_summit_austinResult">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="event_key" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="active" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="title" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="session_start" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="session_end" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="type" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="description" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="seats" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="attendees" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="venue_id" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="venue" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="speakers" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="created" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="modified" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="event_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
</Database>