<?xml version="1.0" encoding="utf-8"?><Database Name="fntech_signage" Class="schedDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=198.178.124.58;Initial Catalog=fntech_signage;Persist Security Info=True;User ID=sa" SettingsObjectName="schedInterface.Properties.Settings" SettingsPropertyName="fntech_signageConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.sessions" Member="sessions">
    <Type Name="session">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="event_key" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="active" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="title" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="session_start" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="session_end" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="type" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="description" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="seats" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="attendees" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="venue_id" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="venue" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="speakers" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="created" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="modified" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="event_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.locations" Member="locations">
    <Type Name="location">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="sched_id" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="title" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="event_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.overlays" Member="overlays">
    <Type Name="overlay">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="title" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="html" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="preview" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="active" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.resolutions" Member="resolutions">
    <Type Name="resolution">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="title" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="width" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="height" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.[log]" Member="logs">
    <Type Name="log">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="event_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="logdate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="user_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="title" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="description" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.permissions" Member="permissions">
    <Type Name="permission">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="event_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="user_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="permission_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="assigned_date" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="assigned_by" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.security" Member="securities">
    <Type Name="security">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="title" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="description" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="active" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.users" Member="users">
    <Type Name="user">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="first_name" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="last_name" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="email" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="company" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="created" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="active" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="notify_every_minutes" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="pic" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="pwd" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="security" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.terminals" Member="terminals">
    <Type Name="terminal">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="title" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="location_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="template_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="online" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="event_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.events" Member="events">
    <Type Name="event">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="title" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="event_start" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="event_end" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="api_key" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="url" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="interval" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="last_update" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="t_username" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="t_hashtag" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.templates" Member="templates">
    <Type Name="template">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="title" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="event_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="orientation" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="resolution" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="bgcolor" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="bgimage" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="overlay" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="overlay_font" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="overlay_font_color" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="rotate_ads" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="ad_interval" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="t_username" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="t_hashtag" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.media" Member="medias">
    <Type Name="media">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="service" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="username" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="full_name" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="description" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="createdate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="profilepic" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="link" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="likes" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="latitude" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="longitude" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="approved" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="approved_by" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="approved_date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="added_to_db_date" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="location_name" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="source_id" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="width" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="height" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="is_video" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="source" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="tags" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="event_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="template_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Function Name="dbo.permissions_get_by_user" Method="permissions_get_by_user">
    <Parameter Name="user_id" Type="System.Int32" DbType="Int" />
    <ElementType Name="permissions_get_by_userResult">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="event_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="user_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="permission_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="assigned_date" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="assigned_by" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="title" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="security_level" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="full_name" Type="System.String" DbType="VarChar(101)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.events_get_authorized" Method="events_get_authorized">
    <Parameter Name="user_id" Type="System.Int32" DbType="Int" />
    <ElementType Name="events_get_authorizedResult">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="title" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="event_start" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="event_end" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="api_key" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="url" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="interval" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="last_update" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.events_to_update" Method="events_to_update">
    <ElementType Name="events_to_updateResult">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="title" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="event_start" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="event_end" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="api_key" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="url" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="interval" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="last_update" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="t_username" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="t_hashtag" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.templates_by_event" Method="templates_by_event">
    <Parameter Name="id" Type="System.Int32" DbType="Int" />
    <ElementType Name="templates_by_eventResult">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="title" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="event_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="orientation" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="resolution" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="bgcolor" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="bgimage" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="overlay" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="overlay_font" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="overlay_font_color" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="rotate_ads" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="ad_interval" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="t_username" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="t_hashtag" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="overlay_title" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.terminal_assignments_by_event" Method="terminal_assignments_by_event">
    <Parameter Name="id" Type="System.Int32" DbType="Int" />
    <ElementType Name="terminal_assignments_by_eventResult">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="title" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="location_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="template_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="online" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="event_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="location_title" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="template_title" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
    </ElementType>
  </Function>
</Database>